import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        background: "#131313",
        "surface-tint": "#00dbe9",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-error": "#690005",
        "tertiary-container": "#d9d9d9",
        "surface-container": "#201f1f",
        "surface-bright": "#393939",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed": "#1a1c1c",
        outline: "#849495",
        error: "#ffb4ab",
        "primary-container": "#00f0ff",
        "on-tertiary": "#2f3131",
        "on-secondary": "#4b007e",
        "primary-fixed-dim": "#00dbe9",
        "surface-dim": "#131313",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#00363a",
        tertiary: "#f5f5f5",
        "on-secondary-fixed-variant": "#6717a5",
        "secondary-container": "#6717a5",
        "on-primary-fixed-variant": "#004f54",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#e2e2e2",
        surface: "#131313",
        "on-secondary-fixed": "#2d004f",
        "primary-fixed": "#7df4ff",
        "on-primary-fixed": "#002022",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "on-tertiary-fixed-variant": "#454747",
        "on-secondary-container": "#d3a0ff",
        "secondary-fixed": "#f1daff",
        primary: "#dbfcff",
        "surface-container-high": "#2a2a2a",
        "on-primary-container": "#006970",
        "outline-variant": "#3b494b",
        "secondary-fixed-dim": "#dfb7ff",
        secondary: "#dfb7ff",
        "surface-container-highest": "#353534",
        "inverse-primary": "#006970",
        "on-surface-variant": "#b9cacb",
        "inverse-on-surface": "#313030",
        "on-background": "#e5e2e1",
        "on-tertiary-container": "#5d5f5f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max-width": "1440px",
        "margin-mobile": "20px",
        unit: "8px",
        "margin-desktop": "80px",
      },
      fontFamily: {
        "display-lg": ["Sora", "sans-serif"],
        "display-lg-mobile": ["Sora", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0px", fontWeight: "400" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "1.3", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0px", fontWeight: "400" },
        ],
      },
      maxWidth: {
        "container-max-width": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
